language: node_js

node_js:
  - "node"
  - "lts/*"
  - "7"

notifications:
  email: false

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli

script:
  - npm run svg
  - npm run build